name: Build and Deploy

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Type check
      run: npm run type

    - name: Build
      run: npm run build

  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
